# Generated by Django 4.0.6 on 2022-08-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nomeCliente', models.CharField(max_length=80)),
                ('nomeProduto', models.CharField(max_length=80)),
                ('valorProduto', models.FloatField()),
                ('estadoAtualPedido', models.CharField(choices=[('Recebido', 'Recebido'), ('Confirmado', 'Confirmado'), ('Despachado', 'Despachado')], default='Recebido', max_length=15)),
                ('horarioCriacaoPedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
